### ISSUE TITLE
What kind of file format should be used for training data ?

### ISSUE THREAD

**Issue by stephanepericat** [Alec-Wright/Automated-GuitarAmpModelling#6]
Hello,

I'm using wav files with 44.1k sample rate exported as 32 bit float for sample data.
when I run this training, I get the following warning:

```
unimplemented audio data type conversion...
```

And when I run a prediction using the output model, it seems there is no difference between the original signal and the processed signal. 

I also tried with some of the sample data provided in this repo, and that seems to work fine... can you please detail what kind of file format it is expecting ? sample rate, bit format, length / duration, etc...

Thanks !
Stephane

**Comment by Alec-Wright** [comment]
Hey, 

32 bit float at 44.1k sample rate should be fine. Is the file stereo? I haven't implemented anything to handle stereo currently so I'm not sure what will happen in that case. As for duration, that shouldn't matter.

Thanks,
Alec

**Comment by stephanepericat** [comment]
no it was a mono file. turned out the audio file was corrupted on export. it's working now :) thanks !
